### ISSUE TITLE
Location of Icon Assets

### ISSUE THREAD

**Issue by AlexanderPlaza** [RocketChat/Rocket.Chat.Artwork#1]
Hello,

I've been trying to look for the SVG assets that are used for the various icons on the rocket.chat client. 
![image](https://user-images.githubusercontent.com/16193999/28728125-04930218-738d-11e7-9d49-edcbf7420c3c.png)

Can you have them available or perhaps list how we can extract them from the client or github page?

Warm regards,

Alexander

**Comment by geekgonecrazy** [comment]
The icon set there uses fontello: http://fontello.com/

**Comment by AlexanderPlaza** [comment]
@geekgonecrazy Are all the fonts/icons listed there used by Rocket.Chat client? Or just a select few?

As I look through the list, some of them are clearly used but other ones aren't. I am looking for the ones specifically used within the client, for documentation/manual creation.

**Comment by geekgonecrazy** [comment]
only a subset are used as needed.
